### ISSUE TITLE
install script on mac fail 

### ISSUE THREAD

**Issue by fritzsche** [rhysd/gocaml#16]
thanks so much for this great project!
Just had some minor build issue. I'm using mac with local LLVM install.

script is executing: "go install -a -v ./llvm"
this cause error:
"go install runtime/internal/sys: open /usr/local/go/pkg/darwin_amd64/runtime/internal/sys.a: permission denied"

I found this:
https://github.com/golang/go/issues/6424

and a simple "go install" in ./llvm seems to have solved the issue for me.

2nd issue I come across is that I was missing out
"brew install bdw-gc"
This is documented in the README, but I was processing it top-down. It's might be easier to follow-up if this is mentioned in the begin of the installation procedure as preparation step before running "make".

**Comment by rhysd** [comment]
I did not see this problem... Could you tell me actual commands you input and Go version?

**Comment by fritzsche** [comment]
Version is latest "go1.8.3 darwin/amd64" and I use the installer from the golang.org homepage. Maybe if you are using homebrew you don't see the issue because authorization might be available to overwrite standard lib, while the installer is less permissions.
Regardless the "-a" option enforce the reinstall. According to rsc comments this is a common misunderstood option because "-a" also apply to all dependencies including the standard lib (and my install does not have permission on overwriting standard lib (what does not make sense anyways).
Dropping "-a" should resolve the issue.
よろしくお願いします。

**Comment by rhysd** [comment]
I see. Let me confirm `-a` option behavior. And as you said, yeah, this problem does not occur when `go` is installed with Homebrew because I don't need any permission to modify files in `/usr/local/Cellar/go/...`.

**Comment by fritzsche** [comment]
Thanks! Meanwhile I installed on a complete new machine. It works for me removing "-a". But I have some other issues during install:
1) new go version does not install the llvm dependency correctly
https://github.com/golang/go/issues/18179
This happening when running "go get -d github.com/rhysd/gocaml".
As a workaround in manually cloned LLVM (same way as the install script is doing).
This was not happing on my other machine as I had already LLVM install some years ago.
2) goyacc is not installed by default
It is another dependency better to mention in the documentation 
I run "go get -u golang.org/x/tools/cmd/goyacc"
3) the go version (since 1.7?) do not need GOPATH (but assume ~/go if unset)
As install-script is using it frequently I just put the following line at the begin of the script:
"export GOPATH=$(go env GOPATH)"
(somehow I'm happy to don't need to set GOPATH on my new machine)


Now GoCaml compiles fine on my new machine and I can compile  example programs with it, but I have failing unit tests like this:

--- FAIL: TestEmitExecutable (0.01s)
	emitter_test.go:103: Runtime library (gocamlrt.a) was not found
		Candidates:
		/var/folders/yg/1bjr8j_j3d98hy8yhknhbtdw0000gn/T/go-build205922930/github.com/rhysd/gocaml/codegen/_test/runtime/gocamlrt.a
		src/github.com/rhysd/gocaml/runtime/gocamlrt.a
Seems it does not link the tests agains the runtime environment (gocamlrt.a).
Any advice?
Thanks!

**Comment by rhysd** [comment]
Thank you for your reports. They are helpful because you seem to be a first person attempting to build gocaml.

> new go version does not install the llvm dependency correctly

Umm... I think we should use `git clone` instead of `go get -d` to prevent it. I'll modify doc.

> goyacc is not installed by default

Ah, goyacc installation doc is in Windows section... I'll move it.

> the go version (since 1.7?) do not need GOPATH (but assume ~/go if unset)

You're correct. I'll use `go env GOPATH` instead.

> emitter_test.go:103: Runtime library (gocamlrt.a) was not found

This test should pass with runtime built at `runtime/gocamlrt.a`. For sanitize: Is there `runtime/gocamlrt.a`? At least tests on Travis CI pass. So I think necessary file is not made.

**Comment by rhysd** [comment]
> goyacc is not installed by default

I noticed that `make` does it. Please refer below line. I guess you did not use `make`.

https://github.com/rhysd/gocaml/blob/cb31dfd927367b6125a0d57ee27e64d450a0b1fc/Makefile#L79

**Comment by fritzsche** [comment]
Regarding goyacc you are right I put ~/go/bin too late in the PATH, I assume it was installed all time, but just not in PATH.
Meanwhile I had a look why test in dir codegen (linker.go) failing and found detectRuntimePath() checks GOPATH. Also linker_test.go seems to check the GOPATH. 
As I didn't set this I got the failing test. Meanwhile I just set GOPATH and all test's passing.

Thanks so much for sharing this project. I enjoy reading the coding. 
 僕は先週末初めて住井英二郎先生の理論見付けた。東京から帰国した、飛行機で勉強しました。
そしてgolangとllvm使うとそのminicamlコンパイラ開発したいと思いました。そのコンパイラもある知らなかった。
Sorry for my bad Japanese, but I'm happy I found that already an implementation is available.
Thanks!

**Comment by rhysd** [comment]
> Meanwhile I had a look why test in dir codegen (linker.go) failing and found detectRuntimePath() checks GOPATH

Ah, you're defnitely correct. I need to fix it. Thank you for catchingit.

> Sorry for my bad Japanese, but I'm happy I found that already an implementation is available.
Thanks!

Not bad! It's natural. At least better than my English :flushed:

**Comment by rhysd** [comment]
I believe problems had gone. I'll close this issue, but if you find there are still some problems, please feel free to leave comments here or to create a new issue. Thank you for reporting this.
