### ISSUE TITLE
Suggestions for OS X build instructions

### ISSUE THREAD

**Issue by gacltdev** [rhysd/gocaml#18]
`mkdir $GOPATH/src/github.com/rhysd && cd $GOPATH/src/github.com/rhysd`
 
might be better with -p option, i.e. 

`mkdir -p $GOPATH/src/github.com/rhysd && cd $GOPATH/src/github.com/rhysd`

Additionally, the **realpath** command isn't available on OS X.

```
# On macOS
$ brew install bdw-gc`
```
might be better as 

```
# On macOS
$ brew install bdw-gc
$ brew install coreutils
```

**Comment by rhysd** [comment]
You're correct. I'll fix doc
