### ISSUE TITLE
Math functions now missing?

### ISSUE THREAD

**Issue by cd256** [rhysd/gocaml#19]
In an earlier build, I was able to use C math functions, i.e.

`let c0 = cos angle in ...`

In the latest build, I am now receiving this error

`Note: Alpha transform failed ...`

Do those functions now have to be wrapped?

**Comment by rhysd** [comment]
All functions imported from C is defined [here](https://github.com/rhysd/gocaml/blob/master/runtime/gocamlrt.c). Math functions are not defined yet.

I'm not sure which they should be implemented, in gocaml or in C. Anyway, yeah, importing math functions is better than never.

**Comment by rhysd** [comment]
I added math functions in f37e33c. Please check it out.
