### ISSUE TITLE
Q: go interoperability

### ISSUE THREAD

**Issue by wklm** [rhysd/gocaml#20]
hey,
Very cool project! Is it fully interoperable with golang packages?

cheers,
Wojtek

**Comment by rhysd** [comment]
I don't aim it for now. This is a totally new programming language and not assumed to be used with Go. GoCaml has an interoperability with C for using many C libraries. So it may be possible to use Go's functions through C.

GoCaml is implemented in Go, but it's not an interpreter, but a compiler from source to LLVM IR. So it's not easy to introduce Go interoperability. It's like introducing Go interoperability to C compiler.
